import React from "react";
import "./globals.css";
import Header from "@/components/header";
import FooterSection from "@/components/footer";
import { Poppins } from "next/font/google";
import Image from "next/image";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="/globals.css" />
      </head>
      <body className={poppins.className}>
        <Header />
        <div className="">{children}</div>
        <FooterSection />
      </body>
    </html>
  );
}
